#!/usr/bin/env python3
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    web_dir = os.path.join(project_dir, 'web')
    output_file = os.path.join(project_dir, 'src', 'web_assets.rs')

    # Read files
    with open(os.path.join(web_dir, 'index.html'), 'r', encoding='utf-8') as f:
        index_html = f.read()

    with open(os.path.join(web_dir, 'style.css'), 'r', encoding='utf-8') as f:
        style_css = f.read()

    with open(os.path.join(web_dir, 'app.js'), 'r', encoding='utf-8') as f:
        app_js = f.read()

    # Generate src/web_assets.rs
    content = f"""// This file is auto-generated by scripts/pack_assets.py.
// Do not edit this file manually.

pub const INDEX_HTML: &str = r###"{index_html}"###;
pub const STYLE_CSS: &str = r###"{style_css}"###;
pub const APP_JS: &str = r###"{app_js}"###;
"""

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print("Successfully packed static assets into src/web_assets.rs")

if __name__ == '__main__':
    main()
