// This file is auto-generated by scripts/pack_assets.py.
// Do not edit this file manually.

pub const INDEX_HTML: &str = r###"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PowerScraper Dashboard</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/style.css">
</head>
<body>

    <aside>
        <div class="logo">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: var(--primary)"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg>
            PowerScraper
        </div>
        <nav>
            <button class="nav-btn active" onclick="switchTab('tab-dashboard', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>
                Dashboard
            </button>
            <button class="nav-btn" onclick="switchTab('tab-mqtt', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path></svg>
                MQTT Settings
            </button>
            <button class="nav-btn" onclick="switchTab('tab-hardware', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"></rect><rect x="2" y="14" width="20" height="8" rx="2" ry="2"></rect><line x1="6" y1="6" x2="6.01" y2="6"></line><line x1="6" y1="18" x2="6.01" y2="18"></line></svg>
                Hardware Drivers
            </button>
            <button class="nav-btn" onclick="switchTab('tab-battery', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="16" height="10" rx="2" ry="2"></rect><line x1="22" y1="11" x2="22" y2="13"></line></svg>
                Battery Control
            </button>
            <button class="nav-btn" onclick="switchTab('tab-periods', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                TOU Periods
            </button>
            <button class="nav-btn" onclick="switchTab('tab-forwarders', this)">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"></path></svg>
                Forwarders
            </button>
        </nav>
    </aside>

    <main>
        <header>
            <h1 id="page-title">System Dashboard</h1>
            <button class="btn-apply" onclick="saveConfiguration()">Apply Changes</button>
        </header>

        <!-- DASHBOARD TAB -->
        <div id="tab-dashboard" class="tab-content active">
            <div class="grid-3">
                <div class="glass-card">
                    <div class="card-title">Mains Grid Power</div>
                    <div class="stat-val" id="stat-mains">0 W</div>
                </div>
                <div class="glass-card">
                    <div class="card-title">Power Manager Mode</div>
                    <div class="stat-val" id="stat-mode" style="color: var(--primary); text-shadow: 0 0 10px var(--primary-glow);">Auto</div>
                </div>
                <div class="glass-card">
                    <div class="card-title">Grid Regulate Target</div>
                    <div class="stat-val" id="stat-target" style="color: var(--warning); text-shadow: 0 0 10px rgba(245,158,11,0.2);">0 W</div>
                </div>
            </div>

            <div class="glass-card">
                <div class="card-title">Live Control Modes</div>
                <div class="mode-container">
                    <div class="mode-card" id="mode-auto" onclick="setInstantMode('Auto')">
                        <h3>Auto Mode</h3>
                        <p>Regulate grid export/import dynamically</p>
                    </div>
                    <div class="mode-card" id="mode-charge" onclick="setInstantMode('ChargeBatteries')">
                        <h3>Charge Batteries</h3>
                        <p>Force maximum battery charging rate</p>
                    </div>
                    <div class="mode-card" id="mode-feedin" onclick="setInstantMode('MaximumFeedin')">
                        <h3>Maximum Feedin</h3>
                        <p>Force maximum battery discharge rate</p>
                    </div>
                </div>
                <div class="form-group" style="margin-top: 10px;">
                    <label for="instant-target">Change Grid Target (W)</label>
                    <div style="display: flex; gap: 15px; align-items: center;">
                        <input type="range" id="instant-target-slider" min="-5000" max="5000" step="50" style="flex: 1; accent-color: var(--primary);" oninput="updateTargetText(this.value)">
                        <input type="number" id="instant-target-val" style="width: 100px;" onchange="updateTargetText(this.value)">
                        <button class="sub-btn" onclick="applyInstantTarget()">Set Target</button>
                    </div>
                </div>
            </div>

            <div class="glass-card">
                <div class="card-title">Inverter Telemetry</div>
                <div class="inverter-list-dashboard" id="dash-inverters-list">
                    <div class="inverter-item" style="color: var(--text-muted); text-align: center; grid-template-columns: 1fr;">No inverters connected.</div>
                </div>
            </div>
        </div>

        <!-- MQTT SETTINGS TAB -->
        <div id="tab-mqtt" class="tab-content">
            <div class="glass-card">
                <div class="card-title">MQTT Broker Credentials</div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="mqtt-broker">Broker Hostname / IP</label>
                        <input type="text" id="mqtt-broker" placeholder="mqtt.example.com">
                    </div>
                    <div class="form-group">
                        <label for="mqtt-port">Broker Port</label>
                        <input type="number" id="mqtt-port" placeholder="1883">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="mqtt-username">Username</label>
                        <input type="text" id="mqtt-username" placeholder="Optional">
                    </div>
                    <div class="form-group">
                        <label for="mqtt-password">Password</label>
                        <input type="password" id="mqtt-password" placeholder="Optional">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="mqtt-base">Base Topic Path</label>
                        <input type="text" id="mqtt-base" placeholder="sensors">
                    </div>
                </div>
                <div class="checkbox-group">
                    <input type="checkbox" id="mqtt-ha-discovery">
                    <label for="mqtt-ha-discovery">Enable Home Assistant MQTT Auto-Discovery</label>
                </div>
                <div class="form-row" style="margin-top: 15px;">
                    <div class="form-group" id="mqtt-ha-prefix-group">
                        <label for="mqtt-ha-prefix">Home Assistant Auto-Discovery Prefix</label>
                        <input type="text" id="mqtt-ha-prefix" placeholder="homeassistant">
                    </div>
                </div>
            </div>
        </div>

        <!-- HARDWARE DRIVERS TAB -->
        <div id="tab-hardware" class="tab-content">
            <!-- SolaX Wifi -->
            <div class="glass-card">
                <div class="card-title">
                    SolaX Wi-Fi HTTP API
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="wifi-enable" onchange="toggleFormSection('wifi-section', this.checked)">
                        <label for="wifi-enable">Enable</label>
                    </div>
                </div>
                <div id="wifi-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="wifi-poll">Poll Period (seconds)</label>
                            <input type="number" id="wifi-poll">
                        </div>
                        <div class="form-group">
                            <label for="wifi-timeout">Request Timeout (seconds)</label>
                            <input type="number" id="wifi-timeout">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="wifi-inverters">WiFi Inverters (IPs or Hostnames, comma separated)</label>
                        <input type="text" id="wifi-inverters" placeholder="e.g. 192.168.1.15, 192.168.1.16">
                    </div>
                </div>
            </div>

            <!-- SolaX Modbus -->
            <div class="glass-card">
                <div class="card-title">
                    SolaX Modbus TCP (Standard)
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="modbus-enable" onchange="toggleFormSection('modbus-section', this.checked)">
                        <label for="modbus-enable">Enable</label>
                    </div>
                </div>
                <div id="modbus-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modbus-poll">Poll Period (seconds)</label>
                            <input type="number" id="modbus-poll">
                        </div>
                        <div class="form-group">
                            <label for="modbus-timeout">Timeout (seconds)</label>
                            <input type="number" id="modbus-timeout">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modbus-pwd">Installer Password</label>
                            <input type="number" id="modbus-pwd">
                        </div>
                        <div class="form-group">
                            <label for="modbus-avg">Power Budget Avg Samples</label>
                            <input type="number" id="modbus-avg">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="modbus-inverters">Inverters List (Comma separated names)</label>
                            <input type="text" id="modbus-inverters" placeholder="e.g. solax1, solax2">
                        </div>
                        <div class="form-group">
                            <label for="modbus-hostnames">Hostnames/Endpoints (Comma separated host:port)</label>
                            <input type="text" id="modbus-hostnames" placeholder="e.g. 192.168.1.20:502, 192.168.1.21:502">
                        </div>
                    </div>
                </div>
            </div>

            <!-- SolaX XHybrid Modbus -->
            <div class="glass-card">
                <div class="card-title">
                    SolaX XHybrid Modbus TCP
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="hybrid-enable" onchange="toggleFormSection('hybrid-section', this.checked)">
                        <label for="hybrid-enable">Enable</label>
                    </div>
                </div>
                <div id="hybrid-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="hybrid-poll">Poll Period (seconds)</label>
                            <input type="number" id="hybrid-poll">
                        </div>
                        <div class="form-group">
                            <label for="hybrid-timeout">Timeout (seconds)</label>
                            <input type="number" id="hybrid-timeout">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="hybrid-pwd">Installer Password</label>
                            <input type="number" id="hybrid-pwd">
                        </div>
                        <div class="form-group">
                            <label for="hybrid-avg">Power Budget Avg Samples</label>
                            <input type="number" id="hybrid-avg">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="hybrid-inverters">Inverters List (Comma separated names)</label>
                            <input type="text" id="hybrid-inverters" placeholder="e.g. solax-x1">
                        </div>
                        <div class="form-group">
                            <label for="hybrid-hostnames">Hostnames/Endpoints (Comma separated host:port)</label>
                            <input type="text" id="hybrid-hostnames" placeholder="e.g. 192.168.1.25:502">
                        </div>
                    </div>
                </div>
            </div>

            <!-- SDM630 Meter -->
            <div class="glass-card">
                <div class="card-title">
                    Eastron SDM630 Serial Meter
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="sdm-enable" onchange="toggleFormSection('sdm-section', this.checked)">
                        <label for="sdm-enable">Enable</label>
                    </div>
                </div>
                <div id="sdm-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="sdm-poll">Poll Period (seconds)</label>
                            <input type="number" id="sdm-poll">
                        </div>
                        <div class="form-group">
                            <label for="sdm-timeout">Timeout (seconds)</label>
                            <input type="number" id="sdm-timeout">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="sdm-baud">Baud Rate</label>
                            <input type="number" id="sdm-baud" placeholder="38400">
                        </div>
                        <div class="form-group">
                            <label for="sdm-parity">Parity</label>
                            <select id="sdm-parity">
                                <option value="N">None (N)</option>
                                <option value="E">Even (E)</option>
                                <option value="O">Odd (O)</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="sdm-stop">Stop Bits</label>
                            <input type="number" id="sdm-stop" placeholder="1">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="sdm-ports">Serial Port TTY Paths (Comma separated)</label>
                        <input type="text" id="sdm-ports" placeholder="e.g. /dev/ttyUSB0">
                    </div>
                </div>
            </div>

            <!-- DTSU666 Meter -->
            <div class="glass-card">
                <div class="card-title">
                    Chint DTSU666 Serial Meter
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="dtsu-enable" onchange="toggleFormSection('dtsu-section', this.checked)">
                        <label for="dtsu-enable">Enable</label>
                    </div>
                </div>
                <div id="dtsu-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="dtsu-poll">Poll Period (seconds)</label>
                            <input type="number" id="dtsu-poll">
                        </div>
                        <div class="form-group">
                            <label for="dtsu-timeout">Timeout (seconds)</label>
                            <input type="number" id="dtsu-timeout">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="dtsu-baud">Baud Rate</label>
                            <input type="number" id="dtsu-baud" placeholder="9600">
                        </div>
                        <div class="form-group">
                            <label for="dtsu-parity">Parity</label>
                            <select id="dtsu-parity">
                                <option value="N">None (N)</option>
                                <option value="E">Even (E)</option>
                                <option value="O">Odd (O)</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="dtsu-stop">Stop Bits</label>
                            <input type="number" id="dtsu-stop" placeholder="1">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="dtsu-ports">Serial Port TTY Paths (Comma separated)</label>
                        <input type="text" id="dtsu-ports" placeholder="e.g. /dev/ttyUSB1">
                    </div>
                </div>
            </div>

            <!-- MQTT Custom Power Meter -->
            <div class="glass-card">
                <div class="card-title">
                    MQTT Custom Power Meter Bridge
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="mqtt-meter-enable" onchange="toggleFormSection('mqtt-meter-section', this.checked)">
                        <label for="mqtt-meter-enable">Enable</label>
                    </div>
                </div>
                <div id="mqtt-meter-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="mqtt-meter-poll">Poll Period (seconds)</label>
                            <input type="number" id="mqtt-meter-poll">
                        </div>
                        <div class="form-group">
                            <label for="mqtt-meter-name">Meter Name</label>
                            <input type="text" id="mqtt-meter-name" placeholder="MainsMeter">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="mqtt-meter-broker">Broker IP/Hostname</label>
                            <input type="text" id="mqtt-meter-broker">
                        </div>
                        <div class="form-group">
                            <label for="mqtt-meter-port">Broker Port</label>
                            <input type="number" id="mqtt-meter-port" placeholder="1883">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="mqtt-meter-user">Username</label>
                            <input type="text" id="mqtt-meter-user" placeholder="Optional">
                        </div>
                        <div class="form-group">
                            <label for="mqtt-meter-pass">Password</label>
                            <input type="password" id="mqtt-meter-pass" placeholder="Optional">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="mqtt-meter-topic-total">Total Power Topic</label>
                            <input type="text" id="mqtt-meter-topic-total">
                        </div>
                        <div class="form-group">
                            <label for="mqtt-meter-topic-p1">Phase 1 Topic</label>
                            <input type="text" id="mqtt-meter-topic-p1">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="mqtt-meter-topic-p2">Phase 2 Topic</label>
                            <input type="text" id="mqtt-meter-topic-p2">
                        </div>
                        <div class="form-group">
                            <label for="mqtt-meter-topic-p3">Phase 3 Topic</label>
                            <input type="text" id="mqtt-meter-topic-p3">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- BATTERY CONTROL TAB -->
        <div id="tab-battery" class="tab-content">
            <div class="glass-card">
                <div class="card-title">
                    Battery Control Settings
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="battery-enable" onchange="toggleFormSection('battery-section', this.checked)">
                        <label for="battery-enable">Enable</label>
                    </div>
                </div>
                <div id="battery-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="battery-source">Grid Power Source (Meter Name)</label>
                            <input type="text" id="battery-source" placeholder="e.g. MainsMeter">
                        </div>
                        <div class="form-group">
                            <label for="battery-tz">Local Timezone</label>
                            <input type="text" id="battery-tz" placeholder="e.g. Australia/Sydney">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="battery-grid-target">Grid Regulate Target (W)</label>
                            <input type="number" id="battery-grid-target">
                        </div>
                        <div class="form-group">
                            <label for="battery-init-mode">Initial Mode</label>
                            <select id="battery-init-mode">
                                <option value="Auto">Auto</option>
                                <option value="ChargeBatteries">Charge Batteries</option>
                                <option value="MaximumFeedin">Maximum Feedin</option>
                            </select>
                        </div>
                    </div>
                    <div class="checkbox-group">
                        <input type="checkbox" id="battery-linked">
                        <label for="battery-linked">Enable Linked Batteries (balances charge rates proportionately)</label>
                    </div>

                    <div style="margin-top: 30px;">
                        <div class="card-title">
                            Inverter Constraint Matrix
                            <button class="sub-btn" onclick="addInverterConstraint()">Add Inverter</button>
                        </div>
                        <div id="inverters-constraints-list">
                            <!-- Dynamic inverter constraint cards -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- TOU PERIODS TAB -->
        <div id="tab-periods" class="tab-content">
            <div class="glass-card">
                <div class="card-title">
                    Time-of-Use Periods
                    <button class="sub-btn" onclick="addTOUPeriod()">Add Period</button>
                </div>
                <div id="periods-list-container">
                    <!-- Dynamic periods list -->
                </div>
            </div>
        </div>

        <!-- FORWARDERS TAB -->
        <div id="tab-forwarders" class="tab-content">
            <!-- EmonCMS -->
            <div class="glass-card">
                <div class="card-title">
                    EmonCMS Forwarder
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="emon-enable" onchange="toggleFormSection('emon-section', this.checked)">
                        <label for="emon-enable">Enable</label>
                    </div>
                </div>
                <div id="emon-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="emon-server">EmonCMS Server URL</label>
                            <input type="text" id="emon-server" placeholder="http://emoncms">
                        </div>
                        <div class="form-group">
                            <label for="emon-timeout">Timeout (seconds)</label>
                            <input type="number" id="emon-timeout">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="emon-api">Write API Key</label>
                        <input type="password" id="emon-api">
                    </div>
                </div>
            </div>

            <!-- InfluxDB -->
            <div class="glass-card">
                <div class="card-title">
                    InfluxDB v1.8+ Forwarder
                    <div class="checkbox-group" style="margin: 0;">
                        <input type="checkbox" id="influx-enable" onchange="toggleFormSection('influx-section', this.checked)">
                        <label for="influx-enable">Enable</label>
                    </div>
                </div>
                <div id="influx-section">
                    <div class="form-row">
                        <div class="form-group">
                            <label for="influx-url">InfluxDB Server URL</label>
                            <input type="text" id="influx-url" placeholder="http://localhost:8086">
                        </div>
                        <div class="form-group">
                            <label for="influx-db">Target Database Name</label>
                            <input type="text" id="influx-db">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="influx-measurement">Measurement / Table Name</label>
                            <input type="text" id="influx-measurement">
                        </div>
                        <div class="form-group">
                            <label for="influx-rp">Retention Policy</label>
                            <input type="text" id="influx-rp" placeholder="autogen">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="influx-user">Username</label>
                            <input type="text" id="influx-user" placeholder="Optional">
                        </div>
                        <div class="form-group">
                            <label for="influx-pass">Password</label>
                            <input type="password" id="influx-pass" placeholder="Optional">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script src="/app.js"></script>
</body>
</html>
"###;
pub const STYLE_CSS: &str = r###":root {
    --bg-gradient: linear-gradient(135deg, #0b0d16 0%, #121528 100%);
    --primary: hsl(245, 75%, 64%);
    --primary-glow: hsla(245, 75%, 64%, 0.35);
    --accent: hsl(160, 80%, 45%);
    --accent-glow: hsla(160, 80%, 45%, 0.25);
    --warning: hsl(35, 90%, 55%);
    --danger: hsl(350, 80%, 55%);
    --card-bg: rgba(22, 26, 49, 0.45);
    --border-color: rgba(255, 255, 255, 0.05);
    --text-main: #f0f2fd;
    --text-muted: #8e95bf;
    --sidebar-width: 260px;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Outfit', sans-serif;
    background: var(--bg-gradient);
    color: var(--text-main);
    min-height: 100vh;
    display: flex;
    overflow-x: hidden;
}

/* Sidebar navigation */
aside {
    width: var(--sidebar-width);
    background: rgba(14, 17, 34, 0.85);
    border-right: 1px solid var(--border-color);
    display: flex;
    flex-direction: column;
    padding: 24px;
    position: fixed;
    height: 100vh;
    z-index: 100;
}

.logo {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 20px;
    font-weight: 700;
    color: #fff;
    margin-bottom: 40px;
    background: linear-gradient(to right, #fff, var(--primary));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

nav {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.nav-btn {
    background: none;
    border: none;
    color: var(--text-muted);
    padding: 14px 16px;
    font-size: 15px;
    font-weight: 500;
    text-align: left;
    border-radius: 10px;
    cursor: pointer;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    display: flex;
    align-items: center;
    gap: 12px;
}

.nav-btn:hover, .nav-btn.active {
    color: #fff;
    background: var(--card-bg);
    box-shadow: inset 3px 0 0 var(--primary);
}

.nav-btn.active {
    background: rgba(81, 71, 229, 0.15);
    box-shadow: inset 3px 0 0 var(--primary), 0 4px 15px var(--primary-glow);
}

/* Main layout content */
main {
    margin-left: var(--sidebar-width);
    flex: 1;
    padding: 40px;
    max-width: 1200px;
}

header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 32px;
}

h1 {
    font-size: 28px;
    font-weight: 600;
    letter-spacing: -0.5px;
}

.btn-apply {
    background: linear-gradient(135deg, var(--primary) 0%, #3b2ddb 100%);
    color: #fff;
    border: none;
    padding: 12px 24px;
    border-radius: 10px;
    font-weight: 600;
    cursor: pointer;
    box-shadow: 0 4px 15px var(--primary-glow);
    transition: all 0.3s ease;
}

.btn-apply:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px var(--primary-glow);
}

.btn-apply:active {
    transform: translateY(0);
}

/* Tabs container */
.tab-content {
    display: none;
    animation: fadeIn 0.4s ease-out forwards;
}

.tab-content.active {
    display: block;
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
}

/* Glass Cards */
.glass-card {
    background: var(--card-bg);
    backdrop-filter: blur(12px);
    border: 1px solid var(--border-color);
    border-radius: 16px;
    padding: 24px;
    margin-bottom: 24px;
    box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2);
}

.card-title {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 20px;
    color: #fff;
    border-bottom: 1px solid var(--border-color);
    padding-bottom: 10px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

/* Grid layout helper */
.grid-3 {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
    margin-bottom: 24px;
}

.stat-val {
    font-size: 32px;
    font-weight: 700;
    color: var(--accent);
    margin-top: 8px;
    text-shadow: 0 0 10px var(--accent-glow);
}

/* Mode Selection Cards */
.mode-container {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 16px;
    margin-bottom: 24px;
}

.mode-card {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid var(--border-color);
    border-radius: 12px;
    padding: 20px;
    cursor: pointer;
    transition: all 0.3s ease;
    text-align: center;
}

.mode-card:hover {
    background: rgba(255, 255, 255, 0.05);
    border-color: rgba(255, 255, 255, 0.1);
    transform: translateY(-2px);
}

.mode-card.active {
    border-color: var(--primary);
    background: rgba(81, 71, 229, 0.1);
    box-shadow: 0 0 15px var(--primary-glow);
}

.mode-card h3 {
    font-size: 16px;
    margin-bottom: 6px;
    color: #fff;
}

.mode-card p {
    font-size: 13px;
    color: var(--text-muted);
}

/* Forms styling */
.form-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
    margin-bottom: 16px;
}

.form-group {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.form-group label {
    font-size: 14px;
    font-weight: 500;
    color: var(--text-muted);
}

.form-group input, .form-group select, .form-group textarea {
    background: rgba(14, 17, 34, 0.6);
    border: 1px solid var(--border-color);
    color: var(--text-main);
    padding: 10px 14px;
    border-radius: 8px;
    font-size: 14px;
    font-family: inherit;
    transition: all 0.3s ease;
}

.form-group input:focus, .form-group select:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 8px var(--primary-glow);
}

.checkbox-group {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-top: 10px;
}

.checkbox-group input {
    width: 18px;
    height: 18px;
    accent-color: var(--primary);
    cursor: pointer;
}

/* Period Lists & Buttons */
.sub-btn {
    background: rgba(255, 255, 255, 0.05);
    color: #fff;
    border: 1px solid var(--border-color);
    padding: 8px 16px;
    border-radius: 6px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
}

.sub-btn:hover {
    background: rgba(255, 255, 255, 0.1);
}

.sub-btn.danger {
    background: rgba(244, 63, 94, 0.1);
    border-color: rgba(244, 63, 94, 0.2);
    color: var(--danger);
}

.sub-btn.danger:hover {
    background: rgba(244, 63, 94, 0.2);
}

.list-item-card {
    background: rgba(255, 255, 255, 0.01);
    border: 1px solid var(--border-color);
    border-radius: 10px;
    padding: 16px;
    margin-bottom: 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.list-item-info h4 {
    font-size: 15px;
    color: #fff;
    margin-bottom: 4px;
}

.list-item-info p {
    font-size: 13px;
    color: var(--text-muted);
}

/* Inverters dashboard list */
.inverter-list-dashboard {
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.inverter-item {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    padding: 16px;
    background: rgba(255, 255, 255, 0.02);
    border-radius: 10px;
    border: 1px solid var(--border-color);
    align-items: center;
}

.inverter-field-title {
    font-size: 12px;
    color: var(--text-muted);
    margin-bottom: 4px;
}

.inverter-field-val {
    font-size: 15px;
    font-weight: 600;
    color: #fff;
}
"###;
pub const APP_JS: &str = r###"let currentConfig = {};

// Tab Switching
function switchTab(tabId, el) {
    document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.nav-btn').forEach(b => b.classList.remove('active'));
    document.getElementById(tabId).classList.add('active');
    el.classList.add('active');

    const pageTitle = el.innerText.trim();
    document.getElementById('page-title').innerText = pageTitle === "Dashboard" ? "System Dashboard" : pageTitle;
}

function toggleFormSection(sectionId, enabled) {
    const section = document.getElementById(sectionId);
    if (section) {
        const inputs = section.querySelectorAll('input, select, textarea, button');
        inputs.forEach(input => input.disabled = !enabled);
        section.style.opacity = enabled ? '1' : '0.4';
    }
}

// Fetch telemetry and status updates
async function fetchStatus() {
    try {
        const r = await fetch('/api/status');
        if (!r.ok) return;
        const status = await r.json();

        document.getElementById('stat-mains').innerText = `${status.meter_power.toFixed(0)} W`;
        document.getElementById('stat-mode').innerText = status.active_mode || "Auto";
        document.getElementById('stat-target').innerText = `${status.grid_target.toFixed(0)} W`;

        // Update instantaneous control UI active states
        document.querySelectorAll('.mode-card').forEach(c => c.classList.remove('active'));
        if (status.active_mode === "Auto") document.getElementById('mode-auto').classList.add('active');
        if (status.active_mode === "ChargeBatteries") document.getElementById('mode-charge').classList.add('active');
        if (status.active_mode === "MaximumFeedin") document.getElementById('mode-feedin').classList.add('active');

        // Render inverter lists
        const list = document.getElementById('dash-inverters-list');
        const keys = Object.keys(status.inverters);
        if (keys.length === 0) {
            list.innerHTML = `<div class="inverter-item" style="color: var(--text-muted); text-align: center; grid-template-columns: 1fr;">No inverters connected.</div>`;
        } else {
            list.innerHTML = keys.map(k => {
                const inv = status.inverters[k];
                return `
                    <div class="inverter-item">
                        <div>
                            <div class="inverter-field-title">Inverter ID</div>
                            <div class="inverter-field-val">${k}</div>
                        </div>
                        <div>
                            <div class="inverter-field-title">Battery Capacity (SOC)</div>
                            <div class="inverter-field-val">${inv.battery_capacity} %</div>
                        </div>
                        <div>
                            <div class="inverter-field-title">Charge/Discharge Power</div>
                            <div class="inverter-field-val">${inv.battery_power} W</div>
                        </div>
                        <div>
                            <div class="inverter-field-title">PV Output Power</div>
                            <div class="inverter-field-val">${inv.pv_power} W</div>
                        </div>
                    </div>
                `;
            }).join('');
        }
    } catch (e) {
        console.error("Failed to fetch live stats", e);
    }
}

// Live Target slider updates
function updateTargetText(val) {
    document.getElementById('instant-target-slider').value = val;
    document.getElementById('instant-target-val').value = val;
}

async function setInstantMode(mode) {
    try {
        // To apply instant mode, we modify the active config's initial-mode and save
        const newCfg = JSON.parse(JSON.stringify(currentConfig));
        if (!newCfg.BatteryControl) newCfg.BatteryControl = {};
        newCfg.BatteryControl["initial-mode"] = mode;
        
        const resp = await fetch('/api/config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(newCfg)
        });
        if (resp.ok) {
            currentConfig = newCfg;
            fetchStatus();
        }
    } catch(e) {
        console.error("Failed to change mode", e);
    }
}

async function applyInstantTarget() {
    const targetVal = parseFloat(document.getElementById('instant-target-val').value);
    if (isNaN(targetVal)) return;
    try {
        const newCfg = JSON.parse(JSON.stringify(currentConfig));
        if (!newCfg.BatteryControl) newCfg.BatteryControl = {};
        newCfg.BatteryControl["grid-target"] = targetVal;
        
        const resp = await fetch('/api/config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(newCfg)
        });
        if (resp.ok) {
            currentConfig = newCfg;
            fetchStatus();
        }
    } catch(e) {
        console.error("Failed to set target", e);
    }
}

// Loading configuration to Forms
async function loadConfig() {
    try {
        const r = await fetch('/api/config');
        if (!r.ok) return;
        const config = await r.json();
        currentConfig = config;

        // Load MQTT
        const mqtt = config.MQTT || {};
        document.getElementById('mqtt-broker').value = mqtt.broker || '';
        document.getElementById('mqtt-port').value = mqtt.port || '';
        document.getElementById('mqtt-username').value = mqtt.username || '';
        document.getElementById('mqtt-password').value = mqtt.password || '';
        document.getElementById('mqtt-base').value = mqtt["base-topic"] || '';
        document.getElementById('mqtt-ha-discovery').checked = mqtt["home-assistant-discovery"] !== false;
        document.getElementById('mqtt-ha-prefix').value = mqtt["home-assistant-prefix"] || '';

        // Load WiFi
        const wifi = config["Solax-Wifi"];
        document.getElementById('wifi-enable').checked = !!wifi;
        toggleFormSection('wifi-section', !!wifi);
        if (wifi) {
            document.getElementById('wifi-poll').value = wifi["poll-period"] || 10;
            document.getElementById('wifi-timeout').value = wifi.timeout || 5;
            document.getElementById('wifi-inverters').value = (wifi.inverters || []).join(', ');
        }

        // Load Modbus Standard
        const modbus = config["Solax-Modbus"];
        document.getElementById('modbus-enable').checked = !!modbus;
        toggleFormSection('modbus-section', !!modbus);
        if (modbus) {
            document.getElementById('modbus-poll').value = modbus["poll-period"] || 10;
            document.getElementById('modbus-timeout').value = modbus.timeout || 5;
            document.getElementById('modbus-pwd').value = modbus["installer-password"] || '';
            document.getElementById('modbus-avg').value = modbus["power-budget-avg-samples"] || 30;
            document.getElementById('modbus-inverters').value = (modbus.inverters || []).join(', ');
            document.getElementById('modbus-hostnames').value = (modbus.hostnames || []).join(', ');
        }

        // Load XHybrid Modbus
        const hybrid = config["Solax-XHybrid-Modbus"];
        document.getElementById('hybrid-enable').checked = !!hybrid;
        toggleFormSection('hybrid-section', !!hybrid);
        if (hybrid) {
            document.getElementById('hybrid-poll').value = hybrid["poll-period"] || 10;
            document.getElementById('hybrid-timeout').value = hybrid.timeout || 5;
            document.getElementById('hybrid-pwd').value = hybrid["installer-password"] || '';
            document.getElementById('hybrid-avg').value = hybrid["power-budget-avg-samples"] || 30;
            document.getElementById('hybrid-inverters').value = (hybrid.inverters || []).join(', ');
            document.getElementById('hybrid-hostnames').value = (hybrid.hostnames || []).join(', ');
        }

        // Load SDM630
        const sdm = config.SDM630Modbusv2;
        document.getElementById('sdm-enable').checked = !!sdm;
        toggleFormSection('sdm-section', !!sdm);
        if (sdm) {
            document.getElementById('sdm-poll').value = sdm["poll-period"] || 1;
            document.getElementById('sdm-timeout').value = sdm.timeout || 1;
            document.getElementById('sdm-baud').value = sdm.baud || 38400;
            document.getElementById('sdm-parity').value = sdm.parity || 'E';
            document.getElementById('sdm-stop').value = sdm.stopbits || 1;
            document.getElementById('sdm-ports').value = (sdm.ports || []).join(', ');
        }

        // Load DTSU666
        const dtsu = config.DTSU666;
        document.getElementById('dtsu-enable').checked = !!dtsu;
        toggleFormSection('dtsu-section', !!dtsu);
        if (dtsu) {
            document.getElementById('dtsu-poll').value = dtsu["poll-period"] || 1;
            document.getElementById('dtsu-timeout').value = dtsu.timeout || 1;
            document.getElementById('dtsu-baud').value = dtsu.baud || 9600;
            document.getElementById('dtsu-parity').value = dtsu.parity || 'N';
            document.getElementById('dtsu-stop').value = dtsu.stopbits || 1;
            document.getElementById('dtsu-ports').value = (dtsu.ports || []).join(', ');
        }

        // Load MQTT Power Meter
        const mqMeter = config.MQTTPowerMeter;
        document.getElementById('mqtt-meter-enable').checked = !!mqMeter;
        toggleFormSection('mqtt-meter-section', !!mqMeter);
        if (mqMeter && mqMeter.meters && mqMeter.meters.length > 0) {
            const meterName = mqMeter.meters[0];
            const mDev = mqMeter.meter_devices[meterName] || {};
            document.getElementById('mqtt-meter-poll').value = mqMeter["poll-period"] || 10;
            document.getElementById('mqtt-meter-name').value = meterName || '';
            document.getElementById('mqtt-meter-broker').value = mDev.broker || '';
            document.getElementById('mqtt-meter-port').value = mDev.port || '';
            document.getElementById('mqtt-meter-user').value = mDev.username || '';
            document.getElementById('mqtt-meter-pass').value = mDev.password || '';
            document.getElementById('mqtt-meter-topic-total').value = mDev.topic_total || '';
            document.getElementById('mqtt-meter-topic-p1').value = mDev.topic_phase1 || '';
            document.getElementById('mqtt-meter-topic-p2').value = mDev.topic_phase2 || '';
            document.getElementById('mqtt-meter-topic-p3').value = mDev.topic_phase3 || '';
        }

        // Load Battery Control Config
        const bat = config["Solax-BatteryControl"];
        document.getElementById('battery-enable').checked = !!bat;
        toggleFormSection('battery-section', !!bat);
        if (bat) {
            document.getElementById('battery-source').value = bat.source || '';
            document.getElementById('battery-tz').value = bat.timezone || 'UTC';
            document.getElementById('battery-grid-target').value = bat["grid-target"] || 0.0;
            document.getElementById('battery-init-mode').value = bat["initial-mode"] || 'Auto';
            document.getElementById('battery-linked').checked = bat["linked-batteries"] === true;

            // Load Instant controls defaults
            document.getElementById('instant-target-val').value = bat["grid-target"] || 0.0;
            document.getElementById('instant-target-slider').value = bat["grid-target"] || 0.0;

            // Render inverter constraints list
            const listDiv = document.getElementById('inverters-constraints-list');
            listDiv.innerHTML = '';
            if (bat.inverter) {
                Object.keys(bat.inverter).forEach(name => {
                    const inv = bat.inverter[name];
                    renderInverterConstraintCard(name, inv);
                });
            }
        }

        // Load TOU Periods
        const periodsContainer = document.getElementById('periods-list-container');
        periodsContainer.innerHTML = '';
        if (bat && bat.period) {
            Object.keys(bat.period).forEach(pName => {
                const per = bat.period[pName];
                renderPeriodCard(pName, per);
            });
        }

        // Load EmonCMS
        const emon = config.emoncms;
        document.getElementById('emon-enable').checked = !!emon;
        toggleFormSection('emon-section', !!emon);
        if (emon) {
            document.getElementById('emon-server').value = emon.server || '';
            document.getElementById('emon-timeout').value = emon.timeout || 5;
            document.getElementById('emon-api').value = emon.api_key || '';
        }

        // Load InfluxDB
        const influx = config.influx;
        document.getElementById('influx-enable').checked = !!influx;
        toggleFormSection('influx-section', !!influx);
        if (influx) {
            document.getElementById('influx-url').value = influx.influx_url || '';
            document.getElementById('influx-db').value = influx.influx_database || '';
            document.getElementById('influx-measurement').value = influx.influx_measurement || '';
            document.getElementById('influx-rp').value = influx.influx_retention_policy || 'autogen';
            document.getElementById('influx-user').value = influx.influx_user || '';
            document.getElementById('influx-pass').value = influx.influx_pass || '';
        }
    } catch (e) {
        console.error("Failed to load config backend", e);
    }
}

// Dynamic Card Rendering helpers
function renderInverterConstraintCard(name, inv) {
    const listDiv = document.getElementById('inverters-constraints-list');
    const card = document.createElement('div');
    card.className = 'list-item-card inverter-constraint-card';
    card.innerHTML = `
        <div style="flex: 1; display: flex; flex-direction: column; gap: 10px;">
            <div class="form-row">
                <div class="form-group">
                    <label>Inverter Name</label>
                    <input type="text" class="inv-name" value="${name}">
                </div>
                <div class="form-group">
                    <label>Wiring Phase</label>
                    <input type="number" class="inv-phase" value="${inv.phase || 1}">
                </div>
                <div class="form-group">
                    <label>Max Charge Rate (W)</label>
                    <input type="number" class="inv-max-charge" value="${inv["max-charge"] || 2000}">
                </div>
                <div class="form-group">
                    <label>Max Discharge Rate (W)</label>
                    <input type="number" class="inv-max-discharge" value="${inv["max-discharge"] || 2000}">
                </div>
            </div>
            <div class="form-row">
                <div class="checkbox-group">
                    <input type="checkbox" class="inv-use-total" ${inv["use-total-power"] ? 'checked' : ''}>
                    <label>Regulate Total Grid Power</label>
                </div>
                <div class="checkbox-group">
                    <input type="checkbox" class="inv-grid-control" ${inv["control-grid-power"] ? 'checked' : ''}>
                    <label>Grid Power Control mode</label>
                </div>
            </div>
        </div>
        <button class="sub-btn danger" style="margin-left: 20px;" onclick="this.parentElement.remove()">Remove</button>
    `;
    listDiv.appendChild(card);
}

function addInverterConstraint() {
    renderInverterConstraintCard('new-inverter', {
        phase: 1,
        "max-charge": 2000,
        "max-discharge": 2000,
        "use-total-power": false,
        "control-grid-power": false
    });
}

function renderPeriodCard(pName, per) {
    const container = document.getElementById('periods-list-container');
    const card = document.createElement('div');
    card.className = 'list-item-card period-card';
    card.innerHTML = `
        <div style="flex: 1; display: flex; flex-direction: column; gap: 10px;">
            <div class="form-row">
                <div class="form-group">
                    <label>Period Identifier</label>
                    <input type="text" class="period-name" value="${pName}">
                </div>
                <div class="form-group">
                    <label>Start Time</label>
                    <input type="text" class="period-start" value="${per.start || '00:00:00'}">
                </div>
                <div class="form-group">
                    <label>End Time</label>
                    <input type="text" class="period-end" value="${per.end || '23:59:59'}">
                </div>
                <div class="form-group">
                    <label>Min SOC (%)</label>
                    <input type="number" class="period-min-charge" value="${per["min-charge"] || 20}">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label>Force Discharge Rate (W)</label>
                    <input type="number" class="period-force-discharge" value="${per["force-discharge"] || ''}" placeholder="None">
                </div>
                <div class="checkbox-group">
                    <input type="checkbox" class="period-grid-charge" ${per["grid-charge"] ? 'checked' : ''}>
                    <label>Allow Charging from Grid</label>
                </div>
                <div class="checkbox-group">
                    <input type="checkbox" class="period-grace" ${per.grace ? 'checked' : ''}>
                    <label>Enable Grace Capacity early stops</label>
                </div>
                <div class="checkbox-group">
                    <input type="checkbox" class="period-prefer-battery" ${per["prefer-battery"] ? 'checked' : ''}>
                    <label>Prioritize Battery Charge</label>
                </div>
            </div>
        </div>
        <button class="sub-btn danger" style="margin-left: 20px;" onclick="this.parentElement.remove()">Remove</button>
    `;
    container.appendChild(card);
}

function addTOUPeriod() {
    renderPeriodCard('NewPeriod', {
        start: '00:00:00',
        end: '23:59:59',
        "min-charge": 20,
        "grid-charge": false,
        grace: false,
        "prefer-battery": false
    });
}

// Parsing comma lists
function parseCommaList(val) {
    if (!val.trim()) return [];
    return val.split(',').map(s => s.trim()).filter(s => s.length > 0);
}

// Saving config JSON
async function saveConfiguration() {
    const cfg = {
        MQTT: {
            broker: document.getElementById('mqtt-broker').value,
            port: parseInt(document.getElementById('mqtt-port').value) || 1883,
            "base-topic": document.getElementById('mqtt-base').value || "sensors",
            username: document.getElementById('mqtt-username').value || null,
            password: document.getElementById('mqtt-password').value || null,
            "home-assistant-discovery": document.getElementById('mqtt-ha-discovery').checked,
            "home-assistant-prefix": document.getElementById('mqtt-ha-prefix').value || "homeassistant"
        }
    };

    // Wifi Inverter
    if (document.getElementById('wifi-enable').checked) {
        cfg["Solax-Wifi"] = {
            "poll-period": parseInt(document.getElementById('wifi-poll').value) || 10,
            timeout: parseInt(document.getElementById('wifi-timeout').value) || 5,
            inverters: parseCommaList(document.getElementById('wifi-inverters').value)
        };
    } else {
        cfg["Solax-Wifi"] = null;
    }

    // Modbus Inverter
    if (document.getElementById('modbus-enable').checked) {
        cfg["Solax-Modbus"] = {
            "poll-period": parseInt(document.getElementById('modbus-poll').value) || 10,
            timeout: parseInt(document.getElementById('modbus-timeout').value) || 5,
            "installer-password": parseInt(document.getElementById('modbus-pwd').value) || null,
            "power-budget-avg-samples": parseInt(document.getElementById('modbus-avg').value) || 30,
            inverters: parseCommaList(document.getElementById('modbus-inverters').value),
            hostnames: parseCommaList(document.getElementById('modbus-hostnames').value)
        };
    } else {
        cfg["Solax-Modbus"] = null;
    }

    // XHybrid Inverter
    if (document.getElementById('hybrid-enable').checked) {
        cfg["Solax-XHybrid-Modbus"] = {
            "poll-period": parseInt(document.getElementById('hybrid-poll').value) || 10,
            timeout: parseInt(document.getElementById('hybrid-timeout').value) || 5,
            "installer-password": parseInt(document.getElementById('hybrid-pwd').value) || null,
            "power-budget-avg-samples": parseInt(document.getElementById('hybrid-avg').value) || 30,
            inverters: parseCommaList(document.getElementById('hybrid-inverters').value),
            hostnames: parseCommaList(document.getElementById('hybrid-hostnames').value)
        };
    } else {
        cfg["Solax-XHybrid-Modbus"] = null;
    }

    // SDM630 Meter
    if (document.getElementById('sdm-enable').checked) {
        cfg.SDM630Modbusv2 = {
            "poll-period": parseInt(document.getElementById('sdm-poll').value) || 1,
            timeout: parseInt(document.getElementById('sdm-timeout').value) || 1,
            baud: parseInt(document.getElementById('sdm-baud').value) || 38400,
            parity: document.getElementById('sdm-parity').value || 'E',
            stopbits: parseInt(document.getElementById('sdm-stop').value) || 1,
            ports: parseCommaList(document.getElementById('sdm-ports').value)
        };
    } else {
        cfg.SDM630Modbusv2 = null;
    }

    // DTSU666 Meter
    if (document.getElementById('dtsu-enable').checked) {
        cfg.DTSU666 = {
            "poll-period": parseInt(document.getElementById('dtsu-poll').value) || 1,
            timeout: parseInt(document.getElementById('dtsu-timeout').value) || 1,
            baud: parseInt(document.getElementById('dtsu-baud').value) || 9600,
            parity: document.getElementById('dtsu-parity').value || 'N',
            stopbits: parseInt(document.getElementById('dtsu-stop').value) || 1,
            ports: parseCommaList(document.getElementById('dtsu-ports').value)
        };
    } else {
        cfg.DTSU666 = null;
    }

    // MQTT Custom Meter
    if (document.getElementById('mqtt-meter-enable').checked) {
        const mName = document.getElementById('mqtt-meter-name').value || "MainsMeter";
        cfg.MQTTPowerMeter = {
            "poll-period": parseInt(document.getElementById('mqtt-meter-poll').value) || 10,
            meters: [mName],
            meter_devices: {}
        };
        cfg.MQTTPowerMeter.meter_devices[mName] = {
            broker: document.getElementById('mqtt-meter-broker').value,
            port: parseInt(document.getElementById('mqtt-meter-port').value) || 1883,
            username: document.getElementById('mqtt-meter-user').value || null,
            password: document.getElementById('mqtt-meter-pass').value || null,
            topic_total: document.getElementById('mqtt-meter-topic-total').value || null,
            topic_phase1: document.getElementById('mqtt-meter-topic-p1').value || null,
            topic_phase2: document.getElementById('mqtt-meter-topic-p2').value || null,
            topic_phase3: document.getElementById('mqtt-meter-topic-p3').value || null
        };
    } else {
        cfg.MQTTPowerMeter = null;
    }

    // Battery Control
    if (document.getElementById('battery-enable').checked) {
        cfg["Solax-BatteryControl"] = {
            source: document.getElementById('battery-source').value || null,
            timezone: document.getElementById('battery-tz').value || "UTC",
            "grid-target": parseFloat(document.getElementById('battery-grid-target').value) || 0.0,
            "initial-mode": document.getElementById('battery-init-mode').value || "Auto",
            "linked-batteries": document.getElementById('battery-linked').checked,
            inverter: {},
            period: {}
        };

        // Compile inverters
        document.querySelectorAll('.inverter-constraint-card').forEach(card => {
            const name = card.querySelector('.inv-name').value.trim();
            if (name) {
                cfg["Solax-BatteryControl"].inverter[name] = {
                    phase: parseInt(card.querySelector('.inv-phase').value) || 1,
                    "max-charge": parseFloat(card.querySelector('.inv-max-charge').value) || 2000.0,
                    "max-discharge": parseFloat(card.querySelector('.inv-max-discharge').value) || 2000.0,
                    "use-total-power": card.querySelector('.inv-use-total').checked,
                    "control-grid-power": card.querySelector('.inv-grid-control').checked
                };
            }
        });

        // Compile periods
        document.querySelectorAll('.period-card').forEach(card => {
            const pName = card.querySelector('.period-name').value.trim();
            const forceVal = parseFloat(card.querySelector('.period-force-discharge').value);
            if (pName) {
                cfg["Solax-BatteryControl"].period[pName] = {
                    start: card.querySelector('.period-start').value.trim() || "00:00:00",
                    end: card.querySelector('.period-end').value.trim() || "23:59:59",
                    "min-charge": parseInt(card.querySelector('.period-min-charge').value) || 20,
                    "grid-charge": card.querySelector('.period-grid-charge').checked,
                    "force-discharge": isNaN(forceVal) ? null : forceVal,
                    grace: card.querySelector('.period-grace').checked,
                    "prefer-battery": card.querySelector('.period-prefer-battery').checked
                };
            }
        });
    } else {
        cfg["Solax-BatteryControl"] = null;
    }

    // EmonCMS
    if (document.getElementById('emon-enable').checked) {
        cfg.emoncms = {
            server: document.getElementById('emon-server').value,
            timeout: parseInt(document.getElementById('emon-timeout').value) || 5,
            api_key: document.getElementById('emon-api').value
        };
    } else {
        cfg.emoncms = null;
    }

    // InfluxDB
    if (document.getElementById('influx-enable').checked) {
        cfg.influx = {
            influx_url: document.getElementById('influx-url').value,
            influx_database: document.getElementById('influx-db').value,
            influx_measurement: document.getElementById('influx-measurement').value,
            influx_retention_policy: document.getElementById('influx-rp').value || "autogen",
            influx_user: document.getElementById('influx-user').value,
            influx_pass: document.getElementById('influx-pass').value
        };
    } else {
        cfg.influx = null;
    }

    try {
        const resp = await fetch('/api/config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(cfg)
        });
        if (resp.ok) {
            alert("Configuration updated and live reloaded successfully!");
            currentConfig = cfg;
            loadConfig();
        } else {
            const err = await resp.text();
            alert(`Failed to apply configuration: ${err}`);
        }
    } catch (e) {
        alert(`Network error saving configuration: ${e}`);
    }
}

// Initialize UI
window.addEventListener('load', () => {
    loadConfig();
    fetchStatus();
    setInterval(fetchStatus, 3000); // Poll status every 3s
});
"###;
